# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.IntegerField(choices=[(0, 'Currently a Primary school pupil'), (1, 'Primary school'), (2, 'Secondary school'), (3, 'College/Bachelor degree'), (4, 'masters degree'), (5, 'doctorate degree')]),
        ),
    ]
