# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20171104_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeature',
            name='moviehated',
            field=models.ManyToManyField(blank=True, related_name='hmovie', to='search.movie'),
        ),
    ]
